### ISSUE TITLE
.vue文件中<script>里不能加注释，加了就报错，不知道怎么回事

### ISSUE THREAD

**Issue by sensen1991** [fengcms/vue-demo-cnodejs#4]
Expected exception block, space or tab after '/*' in comment

**Comment by fengcms** [comment]
`/*`后面有空格，删了就好。

**Comment by sensen1991** [comment]
不，把空格删了也不行。我初步查了下好像是.eslinttrc.js  里面改一下配置，我添加了
'semi': [
          'error',
          'always',
          {
              omitLastInOneLineBlock: false
          }
      ],
现在js是可以加分号了，但是还是不能加注释，我还在查原因

**Comment by fengcms** [comment]
你这么纠结，那就把`eslint`关掉就好了么。开启它的作用是团队协作的时候有一个标准的代码规范，便于代码审查以及工作交接。而不是为了把它配得适合你自己的书写习惯。
所以如果你不喜欢，就关掉就好了，不用去配置这个买卖儿。

**Comment by fengcms** [comment]
一直没用过 /* */ 的注释，刚刚测试了一下，没有任何问题，不会报错。
